import { IsArray, IsBoolean, IsInt, IsNotEmpty, IsNumber, IsOptional, IsString, Max, Min } from "class-validator";

export class ThemeDTO{
    @IsNotEmpty()
    @IsString()
    title: string;

    @IsNumber({allowNaN: false})
    @IsInt()
    @IsNotEmpty()
    @Min(1000)
    @Max(50000)
    maxPoints: number;

    @IsOptional()
    @IsBoolean()
    isAutoGenerated: boolean;
}