import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { ThemeEntity } from './entity/theme.entity';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { ThemeDTO } from './dto/theme.dto';
import { GradeService } from 'src/grade/grade.service';
import { IntegrationEntity } from './entity/integration.entity';
import { IntegrationDto } from './dto/integration.dto';
import { createCipheriv, createDecipheriv, randomBytes, scrypt } from 'node:crypto';
import { ConfigService } from '@nestjs/config';


@Injectable()
export class ThemeService {
    key = '';
    constructor(
        @InjectRepository(ThemeEntity) private readonly themeRepository: Repository<ThemeEntity>,
        @InjectRepository(IntegrationEntity) private readonly integratonRepository: Repository<IntegrationEntity>,
        private readonly dataSource: DataSource,
        private readonly gradeService: GradeService,
        private readonly configService: ConfigService
    ){
        this.key = configService.getOrThrow("CIFER_KEY")
    }

    async find(themeId: string): Promise<ThemeEntity | null>{
        const theme = await this.themeRepository.findOne({where: {id: themeId}});
        
        return theme;
    } 

    async isExist(themeId: string): Promise<Boolean> {
        const isExist = !!(await this.themeRepository.findOne({where:{id: themeId}, select: {id: true}}));

        return isExist;
    }

    async isExistByTitle(title: string): Promise<Boolean> {
        const isExist = !!(await this.themeRepository.findOne({where:{title}, select: {title: true}}));

        return isExist;
    }

    async create(theme: ThemeDTO){
        const {title, maxPoints, isAutoGenerated} = theme;
        const isExist = await this.isExistByTitle(title);     
        
        
        
        if(isExist){
            await this.themeRepository.update({title}, {maxPoints, isAutoGenerated});
            return true
        }

        const entity = this.themeRepository.create({
            title,
            maxPoints,
            isAutoGenerated: !!isAutoGenerated,
        });

        try{
            await this.themeRepository.save(entity);
        }
        catch(err){
            throw new BadRequestException('Something went wrong');
        }

        return true;
    }

    async getUserThemes(passport: string) {
        return await this.themeRepository
            .createQueryBuilder('theme')
            .leftJoinAndSelect('theme.grades', 'grade')
            .leftJoinAndSelect('grade.user', 'user')
            .where('user.id = :id', { id: passport })
            .select([
                'theme.id',
                'theme.title',
                'grade.grade',
            ])
            .getMany();
    }

    async get(passport: string){
        const themes = await this.themeRepository.find({select: {id: true}});
        let userThemes = await this.getUserThemes(passport);

        if(themes.length > userThemes.length){
            const missing = themes.filter((val) => {return !userThemes.find((userVal) => val.id === userVal.id)});
            await this.loadGrades(passport, missing);
            console.log('What wrong with you man')
            userThemes = await this.getUserThemes(passport);
        }
        
        let formedData = userThemes.map((val) => {
            const {title, id, grades} = val;

            return {title, id, grade: grades[0].grade};
        });

        return formedData;
    }

    async getGradeSection(theme: string, passport: string): Promise<number | null>{

        const themeData = await this.find(theme);
        const grade: number | undefined = await this.gradeService.getGrade(passport, theme);

        if(!themeData || grade === undefined){
            return null;
        }
        
        const gradeSection = [themeData.maxPoints * 0.2, themeData.maxPoints * 0.5, themeData.maxPoints * 0.84];

        const section: number = gradeSection.findIndex((val, index, obj) => (obj[index-1] | 0) <= grade && grade < val);

        console.log(`Section on gradeSection calculating: ${section}`)

        return section === -1? gradeSection.length-1: section;
    }

    async getGrade(theme: string, passport: string): Promise<number>{
        const grade: number | undefined = await this.gradeService.getGrade(passport, theme);

        return !!grade? grade: 0;
    }

    async loadDefaultGrades(passport: string): Promise<boolean>{
        const themes: ThemeEntity[] = await this.themeRepository.find({select: {id: true}});
        
        return await this.dataSource.transaction(async (manager) => {
            try{
                const grades = await Promise.all(
                    themes.map(theme => this.gradeService.create(passport, theme))
                );
                manager.save(grades);
            }
            catch{
                return false
            }

            return true;
        });

    }
    async loadGrades(passport: string, themes: ThemeEntity[]){
        return await this.dataSource.transaction(async (manager) => {
            try{
                const grades = await Promise.all(
                    themes.map(theme => this.gradeService.create(passport, theme))
                );
                manager.save(grades);
            }
            catch{
                return false
            }

            return true;
        });
    }

    async getAll(){
        //Добавить выборку, возвращать всё в виде одноуровнего объекта.
        return await this.themeRepository.find();
    }

    convertObject(object: {key: string, value: any}){
        return {[object.key]: object.value};
    }
    arrayToObject(array: any[]){
        let target = {};

        for(const element of array){
            target = {...target, ...element};
        }

        return target;
    }
    encrypt(string: string){
        const iv = randomBytes(16);
        const cipher = createCipheriv('aes-256-cbc', this.key, iv);
        let encrypted = cipher.update(string, 'utf8', 'hex');
        encrypted += cipher.final('hex');
        return iv.toString('hex') + ':' + encrypted;
    }
    decrypt(string: string){
        const [ivHex, encrypted] = string.split(':');
        const iv = Buffer.from(ivHex, 'hex');
        const decipher = createDecipheriv('aes-256-cbc', this.key, iv);
        let decrypted = decipher.update(encrypted, 'hex', 'utf8');
        decrypted += decipher.final('utf8');
        return decrypted;
    }

    async createIntegration(dto: IntegrationDto){
        const {name, service, headers, params, themeId, method} = dto;
        
        const headerObject = this.arrayToObject(headers.map(val => this.convertObject(val)));
        const paramsObject = this.arrayToObject(params.map(val => this.convertObject(val)));
        try{
            const oldIntegration = await this.getIntegration(themeId);
            if(oldIntegration !== null) this.integratonRepository.delete({id: oldIntegration.id});

            const theme = await this.find(themeId);
            const stringifiedParams = JSON.stringify(paramsObject);
            const stringifiedHeaders = JSON.stringify(headerObject);
            const paramEncripted = this.encrypt(stringifiedParams);
            const headersEncripted = this.encrypt(stringifiedHeaders);

            if(!theme) throw 400;
            
            const integration = this.integratonRepository.create({
                theme, name, method, service, params: paramEncripted, headers: headersEncripted
            });
            console.log(integration);
            await this.integratonRepository.save(integration);
            return true;
        }
        catch(err){
            console.error(err);
            switch(err){ 
                case 400: throw new BadRequestException('Theme not found');
                default: throw new BadRequestException('Bad request');
            }
        }
    }

    async getIntegration(theme: string){
        const integration = await this.integratonRepository.findOne({
            where: {theme: {id: theme}},
        });
        if(integration !== null) {
            integration.params = JSON.parse(this.decrypt(integration.params));
            integration.headers = JSON.parse(this.decrypt(integration.headers));
        }
        return integration;
    }
}
